# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 1ef7fdce936815c1d44a10c05df5e5d818db27dd26451870eb656f050ea62cadd386a799f2eec3655ba20b094e5c1ef3da628425746dd362690443bb6123e1bf

test:
  secret_key_base: 753685c52dc110400a993299e88d7ae1f6e69b327caacff24badbd6a70092e41a805377726c9d1da65d6625ee4edee139e6c2ec7a715115d98c49f67ac494f64

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
